name: Generate Github-Pages from markdown files

on:
    push:
        branches: [ main ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 18.x ]

        steps:
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}

            - uses: actions/checkout@v2

            - name: Run Export
              run: |
                  export TZ='Asia/Shanghai'
                  npm i --force
                  npm run build
                  echo "www.pizza-era.github.io" >> .vuepress/dist/CNAME

            - name: Deploy Github-Pages
              uses: JamesIves/github-pages-deploy-action@4.1.4
              with:
                  branch: gh-pages
                  folder: .vuepress/dist
